#ifndef   	GET_PBTIES_H_
# define   	GET_PBTIES_H_
#include <stdio.h>
#include "../Classes/String_Matrices.h"
#include "../Classes/Double_Matrices_cont.h"
#include "../Classes/Int_Matrices_cont.h"
#include <../Routines/matrix_handling.h>
#include "./rand.h"
#include "./manip_dates.h"
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_cdf.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include <gsl/gsl_cdf.h>

#include <vector>
using namespace std;

void get_P_SI_M(Double_Matrices_cont mat_PSI_M,
                Double_Matrices_cont mat_mort_female,
                Double_Matrices_cont mat_mort_male,
                Double_Matrices_cont mat_specs,
                Double_Matrices_cont mat_age,
                gsl_vector * vect_time_line,
                double first_year_mort);

void get_P_SI_M_VBT(Double_Matrices_cont mat_PSI_M,
                    Double_Matrices_cont mat_mort_female,
                    Double_Matrices_cont mat_mort_male,
                    Double_Matrices_cont mat_specs,
                    Double_Matrices_cont mat_age,
                    gsl_vector * vect_time_line,
                    gsl_vector * vect_DOR,
                    gsl_vector * vect_AaS,
                    gsl_vector * vect_AaQ);

void get_P_S_I(Double_Matrices_cont mat_P_S_I,
               Double_Matrices_cont mat_PSI_M,
               Double_Matrices_cont mat_exposure,
               double lambda);
void get_P_S_I_3_param(Double_Matrices_cont mat_P_S_I,
                       Double_Matrices_cont mat_exposure,
                       Double_Matrices_cont mat_P_SI_M,
                       Double_Matrices_cont mat_age,
                       Double_Matrices_cont mat_specs,
                       gsl_vector * vect_time_line,
                       gsl_vector * vect_DOR,
                       gsl_vector * vect_AaS,
                       double lambda1,
                       double lambda2,
                       double lambda3);
void get_P_S_I_4_param_model2(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3);


void get_P_S_I_4_param_model3(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3);

void get_P_S_I_5_param_model3(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              gsl_vector * vect_AaQ,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3,
                              double lambda4);

void get_P_S_I_4_param_model4(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3);

void get_P_S_I_5_param_model4(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              gsl_vector * vect_AaQ,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3,
                              double lambda4);

void get_P_S_I_4_param_model5(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3);
void get_P_S_I_5_param_model5(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              gsl_vector * vect_AaQ,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3,
                              double lambda4);


void get_P_S_I_5_param_model6(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              gsl_vector * vect_AaQ,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3,
                              double lambda4);
void get_P_S_I_5_param_model7(Double_Matrices_cont mat_P_S_I,
                              Double_Matrices_cont mat_exposure,
                              Double_Matrices_cont mat_P_SI_M,
                              Double_Matrices_cont mat_age,
                              Double_Matrices_cont mat_specs,
                              gsl_vector * vect_time_line,
                              gsl_vector * vect_DOR,
                              gsl_vector * vect_AaS,
                              gsl_vector * vect_AaQ,
                              double mu,
                              double lambda1,
                              double lambda2,
                              double lambda3,
                              double lambda4);

void get_P_S_S(Double_Matrices_cont P_S_S,
               Double_Matrices_cont P_SI_M,
               Double_Matrices_cont P_S_I);

void get_P_Ii_Ij_baseline(Double_Matrices_cont mat_Ii_Ij_baseline,
                          double gamma);

void update_P_Ii_Ij(Double_Matrices_cont mat_Ii_Ij,
                    Double_Matrices_cont mat_Ii_Ij_baseline,
                    Double_Matrices_cont mat_P_SI_M,
                    unsigned int ind,
                    unsigned int year);

void get_P_SI_R_and_H_k(Double_Matrices_cont mat_P_SI_R,
                        Double_Matrices_cont mat_P_SI_SI,
                        Double_Matrices_cont mat_H_k_per_ind,
                        Double_Matrices_cont mat_P_S_S,
                        Double_Matrices_cont mat_P_S_I,
                        Double_Matrices_cont mat_P_SI_M,
                        Double_Matrices_cont mat_P_Ii_Ij,
                        Double_Matrices_cont mat_P_Ii_Ij_baseline,
                        gsl_vector * vect_time_line,
                        gsl_vector *vect_DOB,
                        gsl_vector *vect_DOR,
                        gsl_vector *vect_DOD,
                        gsl_vector *vect_DODiag,
                        Double_Matrices_cont mat_specs);

double get_likelihood(Double_Matrices_cont mat_P_SI_R,
                      Double_Matrices_cont mat_P_SI_SI,
                      Double_Matrices_cont mat_P_SI_M,
                      vector < vector < int > > &summary_SI_SI,
                      vector < vector < int > > &summary_SI_R,
                      vector < vector < int > > &summary_SI_M);

double wrapped_L_calculation(Double_Matrices_cont mat_P_S_I,
                             Double_Matrices_cont mat_P_S_S,
                             Double_Matrices_cont mat_exposure,
                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                             Double_Matrices_cont mat_P_Ii_Ij,
                             Double_Matrices_cont mat_P_SI_M,
                             Double_Matrices_cont mat_P_SI_R,
                             Double_Matrices_cont mat_P_SI_SI,
                             Double_Matrices_cont mat_H_k_per_ind,
                             Double_Matrices_cont mat_age,
                             Double_Matrices_cont mat_specs,
                             gsl_vector * vect_time_line,
                             gsl_vector * vect_DOR,
                             gsl_vector * vect_AaS,
                             gsl_vector *vect_DOB,
                             gsl_vector *vect_DOD,
                             gsl_vector *vect_DODiag,
                             vector < vector < int > > &summary_SI_SI,
                             vector < vector < int > > &summary_SI_R,
                             vector < vector < int > > &summary_SI_M,
                             double current_lambda1,
                             double current_lambda2,
                             double current_lambda3,
                             double current_gamma);
double wrapped_L_calculation_4_Params_model2(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_gamma);

double wrapped_L_calculation_4_Params_model3(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_gamma);


double wrapped_L_calculation_5_Params_model3(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_gamma);



double wrapped_L_calculation_4_Params_model4(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_gamma);

double wrapped_L_calculation_5_Params_model4(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_gamma);


double wrapped_L_calculation_4_Params_model5(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_gamma);


double wrapped_L_calculation_5_Params_model5(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_gamma);


double wrapped_L_calculation_5_Params_model6(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_gamma);

double wrapped_L_calculation_5_Params_model7(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_gamma);

double wrapped_L_calculation_6_Params_model3(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_theta,
                                             double current_gamma);

double wrapped_L_calculation_6_Params_model5(Double_Matrices_cont mat_P_S_I,
                                             Double_Matrices_cont mat_P_S_S,
                                             Double_Matrices_cont mat_exposure,
                                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                             Double_Matrices_cont mat_P_Ii_Ij,
                                             Double_Matrices_cont mat_P_SI_M,
                                             Double_Matrices_cont mat_P_SI_R,
                                             Double_Matrices_cont mat_P_SI_SI,
                                             Double_Matrices_cont mat_H_k_per_ind,
                                             Double_Matrices_cont mat_age,
                                             Double_Matrices_cont mat_specs,
                                             gsl_vector * vect_time_line,
                                             gsl_vector * vect_DOR,
                                             gsl_vector * vect_AaS,
                                             gsl_vector * vect_AaQ,
                                             gsl_vector *vect_DOB,
                                             gsl_vector *vect_DOD,
                                             gsl_vector *vect_DODiag,
                                             vector < vector < int > > &summary_SI_SI,
                                             vector < vector < int > > &summary_SI_R,
                                             vector < vector < int > > &summary_SI_M,
                                             double current_mu,
                                             double current_lambda1,
                                             double current_lambda2,
                                             double current_lambda3,
                                             double current_lambda4,
                                             double current_theta,
                                             double current_gamma);

void scale_P_Ii_Ij(Double_Matrices_cont mat_Ii_Ij_baseline,
                   double gamma,
                   double theta,
                   double age);

void  get_P_SI_R_and_H_k_gamma_t(Double_Matrices_cont mat_P_SI_R,
                                 Double_Matrices_cont mat_P_SI_SI,
                                 Double_Matrices_cont mat_H_k_per_ind,
                                 Double_Matrices_cont mat_P_S_S,
                                 Double_Matrices_cont mat_P_S_I,
                                 Double_Matrices_cont mat_P_SI_M,
                                 Double_Matrices_cont mat_P_Ii_Ij,
                                 Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                 vector < vector < int > > &summary_SI_SI,
                                 gsl_vector * vect_time_line,
                                 gsl_vector *vect_DOB,
                                 gsl_vector *vect_DOR,
                                 gsl_vector *vect_DOD,
                                 gsl_vector *vect_DODiag,
                                 Double_Matrices_cont mat_specs,
                                 double current_theta,
                                 double current_gamma);

unsigned int candidate_acceptance(double current_L,
                                  double previous_L);

unsigned int candidate_acceptance_log(double current_L,
                                      double previous_L,
                                      double current_param,
                                      double previous_param);

unsigned int metropolis_step(Double_Matrices_cont mat_P_S_I,
                             Double_Matrices_cont mat_P_S_S,
                             Double_Matrices_cont mat_exposure,
                             Double_Matrices_cont mat_P_Ii_Ij_baseline,
                             Double_Matrices_cont mat_P_Ii_Ij,
                             Double_Matrices_cont mat_P_SI_M,
                             Double_Matrices_cont mat_P_SI_R,
                             Double_Matrices_cont mat_P_SI_SI,
                             Double_Matrices_cont mat_H_k_per_ind,
                             Double_Matrices_cont mat_age,
                             Double_Matrices_cont mat_specs,
                             gsl_vector * vect_time_line,
                             gsl_vector * vect_DOR,
                             gsl_vector * vect_AaS,
                             gsl_vector * vect_AaQ,
                             gsl_vector *vect_DOB,
                             gsl_vector *vect_DOD,
                             gsl_vector *vect_DODiag,
                             vector < vector < int > > &summary_SI_SI,
                             vector < vector < int > > &summary_SI_R,
                             vector < vector < int > > &summary_SI_M,
                             Double_Matrices_cont mat_history,
                             unsigned int iter,
                             unsigned int param_id,
                             double sigma);

unsigned int metropolis_step_multiv(Double_Matrices_cont mat_P_S_I,
                                    Double_Matrices_cont mat_P_S_S,
                                    Double_Matrices_cont mat_exposure,
                                    Double_Matrices_cont mat_P_Ii_Ij_baseline,
                                    Double_Matrices_cont mat_P_Ii_Ij,
                                    Double_Matrices_cont mat_P_SI_M,
                                    Double_Matrices_cont mat_P_SI_R,
                                    Double_Matrices_cont mat_P_SI_SI,
                                    Double_Matrices_cont mat_H_k_per_ind,
                                    Double_Matrices_cont mat_age,
                                    Double_Matrices_cont mat_specs,
                                    gsl_vector * vect_time_line,
                                    gsl_vector * vect_DOR,
                                    gsl_vector * vect_AaS,
                                    gsl_vector * vect_AaQ,
                                    gsl_vector *vect_DOB,
                                    gsl_vector *vect_DOD,
                                    gsl_vector *vect_DODiag,
                                    vector < vector < int > > &summary_SI_SI,
                                    vector < vector < int > > &summary_SI_R,
                                    vector < vector < int > > &summary_SI_M,
                                    Double_Matrices_cont mat_history,
                                    unsigned int iter,
                                    gsl_vector * theta,
                                    gsl_matrix * L);

double adaptive_step(unsigned int nb_accepted,
                     unsigned int iter,
                     unsigned int iter_adaptive,
                     double sigma,
                     double adaptive_lowerbound,
                     double adaptive_upperbound);

double adaptive_step_multiv(unsigned int iter,
                            unsigned int n_iter_adaptive,
                            Double_Matrices_cont mat_history,
                            gsl_matrix* hat_sigma);

int factorial(int n);


#endif 	    /* !GET_PBTIES_H_ */
